### ISSUE TITLE
使用light-ui组件后build报错

### ISSUE THREAD

**Issue by QwangMobile** [chameleon-team/light-ui#1]
chameleon-tool: 1.0.5
light-ui: 0.0.2

cml wx build 报错信息:
`static/js/npm/_cmlkit/light-ui/components/light-popup/light-popup.js from Uglify
Js
Invalid assignment [static/js/npm/_cmlkit/light-ui/components/light-popup/light-
popup.js:198,60]`

cml web biuld 报错信息：
static/js/cml-mall_88c594b1c6d1971fbd2f.js from UglifyJs
Invalid assignment [static/js/cml-mall_88c594b1c6d1971fbd2f.js:7825,60]

**Comment by jimwmg** [comment]
配置babel-path:https://cmljs.org/docs/config.html#%E9%85%8D%E7%BD%AE-babel-loader-%E5%A4%84%E7%90%86%E7%9A%84%E6%96%87%E4%BB%B6
```javascript
const path = require('path');
cml.config.merge({
  babelPath: [path.resolve(__dirname, 'node_modules/test/')],
});
```

**Comment by QwangMobile** [comment]
已解决：
chameleon.config.js中修改babelPath

const path = require('path');
cml.config.merge({
  babelPath: [path.resolve(__dirname, 'node_modules/@cmlkit/light-ui')],
});
